version: '3.0'

services:
    mysql:
        image: mysql/mysql-server:8.0
        ports:
         - '3306:3306'
        volumes:
         - './data/mysql:/var/lib/mysql'
        environment:
            MYSQL_ROOT_PASSWORD: example
            MYSQL_DATABASE: lightbin
            MYSQL_USER: lightbin
            MYSQL_PASSWORD: password
